define(["./CommentsComponent.ext","../lib/mustache","amd!../lib/underscore","amd!../lib/backbone","./BaseComponent","../Logger","../lib/jquery","css!./CommentsComponent"],function(e,t,i,s,n,o,a){var m=n.extend({processing:function(){var n={};
return n.defaults={dataTemplates:{comments:'<div class="commentsDetails"> {{#user}} {{{user}}}, {{/user}} {{{createdOn}}}</div><div class="commentsBody"> <div class="comment">   {{{comment}}} </div> {{#user}} <div class="operation"> {{#permissions.deletePermission}}   <div class="delete">X</div> {{/permissions.deletePermission}} {{#permissions.archive}}  <div class="archive">X</div> {{/permissions.archive}} </div> {{/user}}</div>',addComments:'<div class="commentsAdd">{{#add}} <div class="addComment">Add Comment</div> <div class="addCommentWrapper">   <textarea class=addCommentText></textarea>   <div class="commentsButtons">   <div class="saveComment">Save</div>   <div class="cancelComment">Cancel</div>   </div> </div>{{/add}}</div>',paginateComments:'<div class="paginate commentPaginate"> {{#active}} <div class="navigateRefresh"> Refresh </div> <div class="navigatePrevious"> Newest Comments </div> <div class="navigateNext"> Oldest Comments </div>{{/active}}</div>'}},n.operations={processOperation:function(e,t,i,s,n){var o={};
switch(e){case"LIST_ALL":o={data:{action:"list",page:n.page,firstResult:n.paginate.firstResult,maxResults:n.paginate.maxResults,where:!1}};
break;case"LIST_ACTIVE":o={data:{action:"list",page:n.page,firstResult:n.paginate.firstResult,maxResults:n.paginate.maxResults}};
break;case"GET_LAST":o={data:{action:"list",page:n.page,firstResult:0,maxResults:1}};
break;case"DELETE_COMMENT":o={data:{action:"delete",page:n.page,commentId:t}};break;
case"ARCHIVE_COMMENT":o={data:{action:"archive",page:n.page,commentId:t}};break;case"ADD_COMMENT":o={data:{action:"add",page:n.page,comment:t}}
}this.requestProcessing(o,e,i,s)},requestProcessing:function(t,s,n,o){var m=this;
t=t||{};var r={type:"GET",url:e.getComments(s),success:function(e){m.requestResponse(e,s,n,o)
},dataType:"json"};r=i.extend({},r,t),a.ajax(r)},resetCollection:function(e){for(var t=n.options.paginate,i=t.activePageNumber*t.pageCommentsSize,s=i+t.pageCommentsSize<e.length?i+t.pageCommentsSize:e.length,o=[],a=i;s>a;a++){var m=new n.CommentModel(e[a]);
o.push(m)}return o},requestResponse:function(e,t,i,s){if("LIST_ALL"==t||"LIST_ACTIVE"==t){var o=n.options.paginate;
o.activePageNumber>0&&o.activePageNumber+1>Math.ceil(e.result.length/o.pageCommentsSize)&&o.activePageNumber--,n.options.queryResult=e.result,i.reset(this.resetCollection(e.result)),0==o.activePageNumber&&e&&"undefined"!=typeof e.result&&0==e.result.length&&(e.result=[{id:0,comment:"No Comments to show!",createdOn:"",elapsedMinutes:"",isArchived:!1,isDeleted:!1,isMe:!0,page:"",user:"",permissions:{add:!1,archive:!1,remove:!1}}],i&&"undefined"!=typeof i&&i.reset(this.resetCollection(e.result)))
}s&&"undefined"!=typeof s&&s.apply(this,[e,i])}},n.CommentModel=s.Model.extend({defaults:{id:0,comment:"Guest User",createdOn:"",elapsedMinutes:"",isArchived:!1,isDeleted:!1,isMe:!0,page:"comments",user:"comments",permissions:{}},initialize:function(){this.set("permissions",n.options.permissions)
}}),n.CommentView=s.View.extend({tagName:"div",className:"commentView",events:{"click .delete":"deleteComment","click .archive":"archiveComment"},initialize:function(e){i.bindAll(this,"render","deleteComment","archiveComment"),this.model=e
},render:function(){return this.$el.append(t.render(n.defaults.dataTemplates.comments,this.attributes)),this.$el
},deleteComment:function(){var e=function(e,t){n.operations.processOperation("LIST_ACTIVE",null,t,null,n.options)
};n.operations.processOperation("DELETE_COMMENT",this.model.get("id"),this.model.collection,e,n.options)
},archiveComment:function(){var e=function(e,t){n.operations.processOperation("LIST_ACTIVE",null,t,null,n.options)
};n.operations.processOperation("ARCHIVE_COMMENT",this.model.get("id"),this.model.collection,e,n.options)
}}),n.CommentsCollection=s.Collection.extend({model:n.CommentModel}),n.CommentsView=s.View.extend({tagName:"div",className:"commentComponent",events:{"click .addComment":"addComment","click .saveComment":"saveComment","click .cancelComment":"cancelComment","click .navigatePrevious":"navigatePrevious","click .navigateNext":"navigateNext","click .navigateRefresh":"navigateRefresh"},initialize:function(e){i.bindAll(this,"render","addComment","saveComment","cancelComment","renderComments","renderSingeComment","addComment","saveComment","cancelComment","navigateNext","navigatePrevious","commentsUpdateNotification"),this.collection=e,this.collection.on("reset",this.renderComments),this.collection.on("commentsUpdateNotification",this.commentsUpdateNotification),this.render()
},render:function(){var e=a("#"+n.options.htmlObject),s=a("<div/>").addClass("commentsGroup");
i(this.collection.models).each(function(e){s.append(this.renderSingeComment(e))},this);
var o=a(t.render(n.defaults.dataTemplates.addComments,n.options.permissions)),m=a(t.render(n.defaults.dataTemplates.paginateComments,n.options.paginate));
this.$el.empty().append(s,o,m),e.html(this.$el),this.updateNavigateButtons()},renderComments:function(){var e=a("#"+n.options.htmlObject+" > div .commentsGroup");
e.empty(),i(this.collection.models).each(function(t){e.append(this.renderSingeComment(t))
},this)},renderSingeComment:function(e){var t=new n.CommentView(e);return t.render()
},addComment:function(){this.showAddComment()},saveComment:function(){var e=this,t=this.$el.find(".addCommentText").val(),i=function(t,i){e.hideAddComment();
var s=n.options.paginate;s.activePageNumber=0,n.operations.processOperation("LIST_ACTIVE",null,i,null,n.options)
};n.operations.processOperation("ADD_COMMENT",t,this.collection,i,n.options)},cancelComment:function(){this.hideAddComment()
},navigateNext:function(){var e=n.options.paginate,t=e.activePageNumber*e.pageCommentsSize;
t+e.pageCommentsSize<n.options.queryResult.length&&(e.activePageNumber++,this.collection.reset(n.operations.resetCollection(n.options.queryResult))),this.commentsUpdateNotification(),this.updateNavigateButtons()
},navigatePrevious:function(){{var e=n.options.paginate;e.activePageNumber}e.activePageNumber>0&&(e.activePageNumber--,this.collection.reset(n.operations.resetCollection(n.options.queryResult))),this.commentsUpdateNotification(),this.updateNavigateButtons()
},navigateRefresh:function(){n.options.paginate;n.options.paginate.activePageNumber=0,n.operations.processOperation("LIST_ACTIVE",null,this.collection,null,n.options),a("div.navigateRefreshPopup:first").remove(),a("div.navigateRefresh:first").stop()
},updateNavigateButtons:function(){var e=n.options.paginate;a(".navigatePrevious").addClass("disabled"),a(".navigateNext").addClass("disabled"),e.activePageNumber>0&&a(".navigatePrevious").removeClass("disabled"),e.activePageNumber+1<Math.ceil(n.options.queryResult.length/e.pageCommentsSize)&&a(".navigateNext").removeClass("disabled")
},commentsUpdateNotification:function(){if(n.options.queryResult.length>0){var e=n.options.queryResult[0].createdOn,t=function(t){if(t.result.length>0)if(t.result[0].createdOn==e);else{var i=a("div.navigateRefresh:first");
if(!a("div.navigateRefreshPopup:first").length){var s=a("<div>").attr("class","navigateRefreshPopup").css("position","absolute").html("New comments, please refresh!").hide();
i.prepend(s);var n=i.position();s.offset({top:n.top-(s.height()+i.height()/2),left:n.left+i.width()/2-s.width()/2}).toggle("bounce",{times:3},"slow");
var o=setInterval(function(){i.effect("highlight",{color:"#c0c0c0"},2e3)},4e3);i.on("click",function(){clearInterval(o)
})}}};n.operations.processOperation("GET_LAST",null,null,t,n.options)}},showAddComment:function(){this.$el.find(".addCommentWrapper").show(),this.$el.find(".paginate").hide(),this.$el.find(".addCommentText").val("")
},hideAddComment:function(){this.$el.find(".addCommentWrapper").hide(),this.$el.find(".paginate").show(),this.$el.find(".addCommentText").val("")
}}),n.start=function(e){if(n.options=e,n.defaults=i.extend({},n.defaults,e.defaults),n.commentsCollection=new n.CommentsCollection,n.operations.processOperation("LIST_ACTIVE",null,n.commentsCollection,null,n.options),n.commentsView=new n.CommentsView(n.commentsCollection),n.options.intervalActive){setInterval(function(){n.commentsCollection.trigger("commentsUpdateNotification")
},n.options.interval)}},n},update:function(){return this.paginateActive="undefined"==typeof this.paginate?!0:this.paginate,this.pageCommentsSize="undefined"==typeof this.pageCommentsSize?10:this.pageCommentsSize,this.firstResult="undefined"==typeof this.firstResult?0:this.firstResult,this.maxResults="undefined"==typeof this.maxResults?100:this.maxResults,this.interval="undefined"==typeof this.interval?6e4:this.interval,this.intervalActive="undefined"==typeof this.intervalActive?!0:this.intervalActive,this.addPermission="undefined"==typeof this.addPermission?!0:this.addPermission,this.deletePermission="undefined"==typeof this.deletePermission?!1:this.deletePermission,this.archivePermission="undefined"==typeof this.archivePermission?!0:this.archivePermission,this.options="undefined"==typeof this.options?{}:this.options,void 0==this.page?(o.error("Fatal - no page definition passed"),void 0):(this.processing().start({htmlObject:this.htmlObject,page:this.page,intervalActive:this.intervalActive,interval:this.interval,paginate:{active:this.paginateActive,activePageNumber:0,pageCommentsSize:this.pageCommentsSize,firstResult:this.firstResult,maxResults:this.maxResults},permissions:{add:this.addPermission,deletePermission:this.deletePermission,archive:this.archivePermission},defaults:this.options}),void 0)
}});return m});