DROP TABLE IF EXISTS CRYSTAL.STG_JMETER_REPORTS;
DROP TABLE IF EXISTS CRYSTAL.OPE_JMETER_REPORTS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_YEARS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_MONTHS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_DAYS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_TESTS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_HOSTS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_HOURS;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_MINUTES;
DROP TABLE IF EXISTS CRYSTAL.DM_DIM_TYPES;
DROP TABLE IF EXISTS CRYSTAL.DM_FACT_LOGS;
DROP SCHEMA IF EXISTS CRYSTAL;

CREATE SCHEMA IF NOT EXISTS CRYSTAL;

CREATE TABLE CRYSTAL.STG_JMETER_REPORTS (
 ELAPSED BIGINT,
 IDLETIME BIGINT,
 LATENCY BIGINT,
 CONNECT BIGINT,
 TIMESTAMP BIGINT,
 SUCCESS VARCHAR(128),
 LABEL VARCHAR(4096),
 RESPONSECODE VARCHAR(128),
 RESPONSEMESSAGE VARCHAR(4096),
 THREADNAME VARCHAR(4096),
 DATATYPE VARCHAR(4096),
 ENCODING VARCHAR(4096),
 BYTES BIGINT,
 SAMPLECOUNT BIGINT,
 ERRORCOUNT BIGINT,
 GROUPTHREADS BIGINT,
 ALLTHREADS BIGINT,
 HOSTNAME VARCHAR(4096),
 FILENAME VARCHAR(4096),
 TYPE VARCHAR(128)
);

CREATE TABLE CRYSTAL.OPE_JMETER_REPORTS
(
 ELAPSED BIGINT,
 IDLETIME BIGINT,
 LATENCY BIGINT,
 CONNECT BIGINT,
 DATETIME TIMESTAMP,
 SUCCESS VARCHAR(128),
 LABEL VARCHAR(4096),
 RESPONSECODE VARCHAR(128),
 RESPONSEMESSAGE VARCHAR(4096),
 THREADNAME VARCHAR(4096),
 DATATYPE VARCHAR(4096),
 ENCODING VARCHAR(4096),
 BYTES BIGINT,
 SAMPLECOUNT BIGINT,
 ERRORCOUNT BIGINT,
 GROUPTHREADS BIGINT,
 ALLTHREADS BIGINT,
 HOSTNAME VARCHAR(4096),
 FILENAME VARCHAR(4096),
 TESTNAME VARCHAR(4096),
 TYPE VARCHAR(128)
);

CREATE TABLE CRYSTAL.DM_DIM_YEARS
(
 ID SMALLINT NOT NULL,
 DESCRIPTION VARCHAR(8) NOT NULL,
 SRC_ID SMALLINT NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_YEARS ADD PRIMARY KEY (ID);

CREATE TABLE CRYSTAL.DM_DIM_MONTHS
(
 ID DATE NOT NULL,
 DESCRIPTION VARCHAR(10) NOT NULL,
 FULL_DESCRIPTION VARCHAR(25) NOT NULL,
 YEAR_ID SMALLINT NOT NULL,
 SRC_ID DATE NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_MONTHS ADD PRIMARY KEY (ID);
ALTER TABLE CRYSTAL.DM_DIM_MONTHS ADD FOREIGN KEY (YEAR_ID) REFERENCES CRYSTAL.DM_DIM_YEARS(ID);

CREATE TABLE CRYSTAL.DM_DIM_DAYS
(
 ID DATE NOT NULL,
 DESCRIPTION VARCHAR(10) NOT NULL,
 FULL_DESCRIPTION VARCHAR(25) NOT NULL,
 WEEK_DAY_DESCRIPTION VARCHAR(20) NOT NULL,
 WEEK_OF_YEAR SMALLINT NOT NULL,
 DAY_OF_WEEK SMALLINT NOT NULL,
 DAY_OF_MONTH SMALLINT NOT NULL,
 DAY_OF_YEAR SMALLINT NOT NULL,
 MONTH_ID DATE NOT NULL,
 SRC_ID DATE NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_DAYS ADD PRIMARY KEY (ID);
ALTER TABLE CRYSTAL.DM_DIM_DAYS ADD FOREIGN KEY (MONTH_ID) REFERENCES CRYSTAL.DM_DIM_MONTHS(ID);

CREATE TABLE CRYSTAL.DM_DIM_TESTS
(
 ID INTEGER NOT NULL AUTO_INCREMENT,
 DESCRIPTION VARCHAR(2048) NOT NULL,
 SRC_ID VARCHAR(2048) NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_TESTS ADD PRIMARY KEY (ID);

CREATE TABLE CRYSTAL.DM_DIM_HOSTS
(
 ID INTEGER NOT NULL AUTO_INCREMENT,
 DESCRIPTION VARCHAR(1024) NOT NULL,
 SRC_ID VARCHAR(1024) NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_HOSTS ADD PRIMARY KEY (ID);

CREATE TABLE CRYSTAL.DM_DIM_HOURS
(
 ID SMALLINT NOT NULL,
 DESCRIPTION VARCHAR(10) NOT NULL,
 DESCRIPTION_AMPM VARCHAR(10) NOT NULL,
 SRC_ID SMALLINT NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_HOURS ADD PRIMARY KEY (ID);

CREATE TABLE CRYSTAL.DM_DIM_MINUTES
(
 ID SMALLINT NOT NULL,
 DESCRIPTION VARCHAR(10) NOT NULL,
 DESCRIPTION_AMPM VARCHAR(10) NOT NULL,
 DESCRIPTION_IN_HOUR VARCHAR(10) NOT NULL,
 MINUTE_IN_HOUR TINYINT NOT NULL,
 HOUR_ID SMALLINT NOT NULL,
 SRC_ID SMALLINT NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_MINUTES ADD PRIMARY KEY (ID);
ALTER TABLE CRYSTAL.DM_DIM_MINUTES ADD FOREIGN KEY (HOUR_ID) REFERENCES CRYSTAL.DM_DIM_HOURS(ID);

CREATE TABLE CRYSTAL.DM_DIM_TYPES
(
 ID SMALLINT NOT NULL,
 DESCRIPTION VARCHAR(128) NOT NULL,
 SRC_ID VARCHAR(128) NOT NULL
);

ALTER TABLE CRYSTAL.DM_DIM_TYPES ADD PRIMARY KEY (ID);

CREATE TABLE CRYSTAL.DM_FACT_LOGS
(
 TEST_ID INTEGER NOT NULL,
 TYPE_ID SMALLINT NOT NULL,
 HOSTNAME_ID INTEGER NOT NULL,
 DAY_ID DATE NOT NULL,
 MINUTE_ID SMALLINT NOT NULL,
 SECOND TINYINT NOT NULL DEFAULT -1,
 MILLISECOND SMALLINT NOT NULL DEFAULT -1,
 THREADNAME VARCHAR(1024) DEFAULT 'Unknown',
 LABEL VARCHAR(1024) DEFAULT 'Unknown',
 SUCCESS VARCHAR(10) DEFAULT 'Unknown',
 ELAPSED BIGINT DEFAULT 0,
 IDLETIME BIGINT DEFAULT 0,
 LATENCY BIGINT DEFAULT 0,
 CONNECT BIGINT DEFAULT 0,
 BYTES BIGINT DEFAULT 0,
 RESPONSE_VALUE DOUBLE DEFAULT 0
);

ALTER TABLE CRYSTAL.DM_FACT_LOGS ADD FOREIGN KEY (TEST_ID) REFERENCES CRYSTAL.DM_DIM_TESTS(ID);
ALTER TABLE CRYSTAL.DM_FACT_LOGS ADD FOREIGN KEY (TYPE_ID) REFERENCES CRYSTAL.DM_DIM_TYPES(ID);
ALTER TABLE CRYSTAL.DM_FACT_LOGS ADD FOREIGN KEY (HOSTNAME_ID) REFERENCES CRYSTAL.DM_DIM_HOSTS(ID);
ALTER TABLE CRYSTAL.DM_FACT_LOGS ADD FOREIGN KEY (DAY_ID) REFERENCES CRYSTAL.DM_DIM_DAYS(ID);
ALTER TABLE CRYSTAL.DM_FACT_LOGS ADD FOREIGN KEY (MINUTE_ID) REFERENCES CRYSTAL.DM_DIM_MINUTES(ID);

