define(["cdf/lib/jquery","cdf/lib/mustache","../base/filter-base-implementation"],function(e,t,n){return e.extend(!0,n.Extensions.Renderers,{group:function(e,n){var o,i,r;
return r=n.toJSON(),i=t.render("{{label}}",r),o=t.render('<a href="http://www.google.com">More about {{label}}</a>',r),e.find(".filter-group-title").html(i),e.find(".filter-group-footer").html(o),e.css({border:"1px solid rgb("+_.random(255)+","+_.random(255)+","+_.random(255)+")"})
},sumSelected:function(e,t){var n,o;return o=t.flatten().filter(function(e){return null==e.children()
}).filter(function(e){return e.getSelection()===!0}).reduce(function(e,t){return e+t.get("value")
},0).value(),n=t.isRoot()?".filter-root-selection-value":".filter-group-selection-value",e.find(n+":eq(0)").html(0===o?"":o)
},Item:function(e){var t;return t={item:"<span>"+viewModel.label+"</span> <span style='float:right;'>comem</>"},e.find(".filter-item-body").html(t.item)
},rootHeaderSingleSelect:function(e,t){var n;return n=t.getSelectedItems()[0]||"None",e.find(".filter-root-header-label").html(n).attr("title",n)
},rootHeaderMultiSelect:function(e,n){var o,i;return i=n.toJSON(),o=t.render('<span class="filter-root-info-number-selected-items">\n  {{numberOfSelectedItems}}\n</span>\n<span class="filter-root-info-number-items">\n  of {{numberOfItems}}\n</span>',i),"undefined"!=typeof console&&null!==console&&console.log("injecting content on header"),e.find(".filter-root-header-label").html(o).attr("title",t.render("{{numberOfSelectedItems}}/{{numberOfItems}}",i)),e.find(".filter-root-header-label").mouseover(function(){return"undefined"!=typeof console&&null!==console?console.log("hovering "+i.label):void 0
})},notificationSelectionLimit:function(n,o,i){var r,l;return l=e.extend(!0,o.toJSON(),i),r=t.render('{{#reachedSelectionLimit}}\n<div class="filter-root-notification">\n  <div class="filter-root-notification-icon" />\n  <div class="filter-root-notification-text">\n    The selection limit\n    (<span class="filter-notification-highlight">{{Root.options.selectionStrategy.limit}}</span>)\n    for specific items has been reached.\n  </div>\n</div>\n{{/reachedSelectionLimit}}',l),n.find(".filter-root-footer").html(r)
}}),n});