define(["cdf/lib/jquery","amd!cdf/lib/underscore","amd!cdf/lib/backbone","cdf/Dashboard.Clean","cdf/components/UnmanagedComponent","./filter/filter-implementation","css!./filter/styles/filter"],function(t,e,n,o,i,r){var s;
return s=function(t,e,n,o,i,r){var s,a,u;return a={getValue:function(){return this._value
},setValue:function(t){return this.inputDataHandler.setValue(t),this},processChange:function(t){return this._value=t,this.dashboard.processChange(this.name),this
}},s={defaults:{component:{},input:{defaultModel:{isDisabled:!0},indexes:{id:0,label:1,parentId:2,parentLabel:3,value:4}},output:{}},getConfiguration:function(){var n,o,i,s,a,u,l,d,h,p,c,m;
return o=this.componentDefinition,i=this.componentInput,s=this.componentOutput,m=this,d=o.multiselect?"LimitedSelect":"SingleSelect",a={input:{},output:{},component:t.extend(!0,{},r.defaults,r.Enum.selectionStrategy[d],{target:this.placeholder()})},t.extend(!0,a,e.result(this,"defaults")),n=function(n,o){var i,r,s,a;
if(r=t.Deferred(),0===this.query.getOption("pageSize"))return r.resolve({}),r;i=e.bind(function(t){return this.inputDataHandler.updateModel(t),this.model.setBusy(!1),r.resolve(t),t
},this),this.model.setBusy(!0);try{switch(a=e.isEmpty(o)?"":o,this.query.setSearchPattern(a),n){case"previous":0!==this.query.getOption("page")&&this.query.previousPage(i);
break;case"next":this.query.nextPage(i);break;default:this.query.setOption("page",n),this.query.doQuery(i)
}}catch(u){s=u,r.reject({}),this.model.setBusy(!1)}return r},c=[],o.showIcons||c.push("no-icons"),l=1/0,null!=this.queryDefinition.pageSize&&e.isFinite(this.queryDefinition.pageSize)&&this.queryDefinition.pageSize>0&&(l=this.queryDefinition.pageSize),t.extend(!0,a.component,{pagination:{pageSize:l,getPage:e.bind(n,this)},selectionStrategy:{limit:e.isNumber(o.selectionLimit)?o.selectionLimit:1/0},Root:{options:{styles:c,alwaysExpanded:o.alwaysExpanded,showFilter:o.showFilter,useOverlay:o.useOverlay},strings:{title:o.title}}}),u=this.dashboard.i18nSupport.map||{},m=this,e.each(["Root","Group","Item"],function(t){return e.each(a.component[t].strings,function(n,o,i){var r;
return r="filter_"+t+"_"+o,e.has(u,r)?i[o]=m.dashboard.i18nSupport.prop(r):void 0
})}),h=a.component.selectionStrategy,p=new r.SelectionStrategies[h.type](h),a.component.selectionStrategy.strategy=p,"SingleSelect"!==h&&(o.showButtonOnlyThis===!0||o.showButtonOnlyThis===!1)&&(a.component.Root.options.showButtonOnlyThis=o.showButtonOnlyThis,a.component.Group.options.showButtonOnlyThis=o.showButtonOnlyThis,a.component.Item.options.showButtonOnlyThis=o.showButtonOnlyThis),t.extend(!0,a.input,this.componentInput,{query:this.query}),t.extend(!0,a.output,this.componentOutput),a=t.extend(!0,a,this._mapAddInsToConfiguration(),e.result(this,"options"))
},_mapAddInsToConfiguration:function(){var t,n,o,i,r;return r=this,n=e.chain(this.addIns).map(function(t,n){var o;
return o=e.chain(t).map(function(t){var e,o,i;return o=t.trim(),e=r.getAddIn(n,o),null!=e?(i=r.getAddInOptions(n,o),function(t,n,o){var s;
return s={model:n,configuration:o,dashboard:r.dashboard},e.call(t,s,i)}):null}).compact().value(),[n,o]
}).object().value(),t={postUpdate:"input.hooks.postUpdate",renderRootHeader:"component.Root.renderers.header",renderRootSelection:"component.Root.renderers.selection",renderRootFooter:"component.Root.renderers.footer",renderGroupSelection:"component.Group.renderers.selection",renderItemSelection:"component.Item.renderers.selection",sortItem:"component.Item.sorter",sortGroup:"component.Group.sorter",outputFormat:"output.outputFormat"},o={},i=function(t,e){return null!=t[e]?t[e]:t[e]={}
},e.each(n,function(r,s){var a,u,l,d;return e.isEmpty(r)?void 0:(u=t[s].split("."),d=e.initial(u),a=e.last(u),l=e.reduce(d,i,o),l[a]=n[s])
}),o}},u=i.extend(a).extend(s).extend({model:void 0,manager:void 0,inputDataHandler:void 0,outputDataHandler:void 0,update:function(){var n,o;
return o=this,n=function(e){var n;return n=new t.Deferred,o.initialize().then(function(){n.resolve(e)
}),n.promise()},this.getData().then(n,e.bind(this.onDataFail,this)).then(e.bind(this.onDataReady,this)),this
},close:function(){return null!=this.manager&&this.manager.walkDown(function(t){return t.isRoot()?void 0:(t.close(),t.remove())
}),null!=this.model&&this.model.stopListening().off(),this.stopListening()},initialize:function(){var e,n;
return e=this.getConfiguration(),this.close(),this.model=new r.Models.SelectionTree(e.input.defaultModel),this.manager=new r.Controllers.Manager({model:this.model,configuration:e.component}),this.inputDataHandler=new r.DataHandlers.Input({model:this.model,options:e.input}),this.outputDataHandler=new r.DataHandlers.Output({model:this.model,options:e.output}),this.listenTo(this.outputDataHandler,"changed",this.processChange),n=new t.Deferred,n.resolve(e),n.promise()
},getData:function(){var n,o,i,s,a;return o=new t.Deferred,n=e.bind(function(t){o.resolve(t)
},this),a=this,e.isEmpty(this.dashboard.detectQueryType(this.queryDefinition))?this.componentInput.inputParameter&&!e.isEmpty(this.componentInput.inputParameter)?(i=this.dashboard.getParameterValue(this.componentInput.inputParameter),this.synchronous(n,i)):this.synchronous(n,this.componentInput.valuesArray):(s={ajax:{error:function(){return o.reject({}),r.Logger.log("Query failed","debug")
}}},this.triggerQuery(this.queryDefinition,n,s)),o.promise()},onDataReady:function(t){var e;
return this.inputDataHandler.updateModel(t),this.parameter&&(e=this.dashboard.getParameterValue(this.parameter),this.setValue(e)),this.trigger("getData:success"),this
},onDataFail:function(){return r.Logger.log("Component failed to retrieve data: #{reason}","debug"),this.trigger("getData:failed"),this
}},{help:function(){return"Filter component"}})}(t,e,n,o,i,r)});