define("cde/components/ViewManager/ViewManagerModel",["amd!cdf/lib/backbone"],function(e){var t=e.Model.extend({defaults:{dashboard:void 0},constructor:function(){e.Model.apply(this,arguments)
}});return t}),define("cde/components/ViewManager/ViewModel",["amd!cdf/lib/backbone"],function(e){var t=e.Model.extend({defaults:{name:"Unsaved",description:"",id:null,params:{},unbound:[],user:"",solution:"",path:"",file:"",timestamp:0},constructor:function(){e.Model.apply(this,arguments)
}});return t}),define("cde/components/ViewManagerComponentExt",[],function(){var e={getViewsEndpoint:function(e){return e&&e.length?CONTEXT_PATH+"plugin/pentaho-cdf/api/views/"+e:CONTEXT_PATH+"plugin/pentaho-cdf/api/views"
},getUrl:function(e,t,a,i){return CONTEXT_PATH+"api/repos/"+((e?e:"")+(t?t:"")+(a?a:"")).replace(/\//g,":").replace(/\+/g,"%20")+"/generatedContent?viewId="+i.replace(/\+/g,"%20")
}};return e}),define("cde/components/ViewManager/ViewCollection",["cdf/Logger","amd!cdf/lib/backbone","./ViewModel","../ViewManagerComponentExt"],function(e,t,a,i){var n=t.Collection.extend({url:function(){return i.getViewsEndpoint()
},model:a,parse:function(t){return"error"===t.status?(e.warn(t.result),void 0):t.result
}});return n}),define("cde/components/ViewManager/ViewManagerView",["cdf/Logger","cdf/lib/jquery","amd!cdf/lib/underscore","amd!cdf/lib/backbone","cdf/lib/base64","./ViewModel","./ViewCollection","../ViewManagerComponentExt"],function(e,t,a,i,n,s,l,o){var r=a.templateSettings;
a.templateSettings={interpolate:/\{\{(.+?)\}\}/g};var c={viewManager:a.template("<div class='view-manager-component'>  <div class='current-view'>    <span class='label'>Current View: </span>    <span class='value'>{{currentView}}</span>  </div>  <div class='big-button manage-views'>Manage Views</div>  <div class='view-manager'>    <div class='tabs'></div>    <div class='tab-contents'></div>  </div></div>"),viewManagerTab:a.template("<div class='tab' data-target='{{selector}}'>  {{label}}</div>"),viewListPanel:a.template("<div class='list-panel panel'>  <div class='total-views'>    <span class='label'>Total Views: </span>    <span class='value'>{{viewCount}}</span>  </div>  <div class='views'></div>  <div class='view-all'>    <span class='label'>View All</span>    <span class='description'>(go to View Manager)</span>  </div></div>"),viewListItem:a.template("<div class='view-item'>  <a class='name' href='{{viewUrl}}'>{{name}}</a>  <span class='delete'></span></div>"),viewSavePanel:a.template("<div class='save-panel panel'>  <div class='current-view'>    <span class='label'>Current View:</span>    <span class='value'>{{currentView}}</span>  </div>  <div class='save-properties'>    <div><span class='label'>Name</span><input type='text' class='name' value='{{currentView}}'></div>    <div><span class='label'>Description</span><textarea class='description' placeholder='Enter a description'>{{description}}</textarea></div>  </div>  <div class='save-actions'>    <div class='big-button active save'>Save</div>    <div class='big-button cancel'>Cancel</div>  </div></div>")};
a.templateSettings=r;var d=i.View.extend({collection:l,events:{"click .tab":"clickTab","click .manage-views, .save-panel .cancel":"toggleViewManager","click .view-item .delete":"deleteView","click .save-panel .save":"saveView"},tabs:[{label:"List",selector:".list-panel",template:"viewListPanel"},{label:"Save",selector:".save-panel",template:"viewSavePanel"}],initialize:function(){this.collection=new l,this.collection.on("add change sync remove",this.render,this),this.collection.fetch()
},render:function(){var e=this.model.get("dashboard").view?this.model.get("dashboard").view.name:void 0,t=this.model.get("dashboard").view?this.model.get("dashboard").view.description:void 0;
if(e){var a=this.collection.filter(function(t){return t.get("name")==e})[0];a?(e=a.get("name"),t=a.get("description")):(e="Unsaved",t="")
}else e="Unsaved",t="";this.$el.html(c.viewManager({currentView:e,views:this.collection,viewCount:this.collection.size()})),this.renderTabs(e,t),this.renderViewList(),this.$(".view-manager").hide()
},renderTabs:function(e,t){var i=this.$(".tabs").empty(),n=this.$(".tab-contents").empty();
a(this.tabs).each(function(a){i.append(c.viewManagerTab(a)),"viewListPanel"===a.template?n.append(c[a.template]({views:this.collection,viewCount:this.collection.size()})):"viewSavePanel"===a.template&&n.append(c[a.template]({currentView:e,description:t}))
},this),i.children().slice(0,1).addClass("selected"),n.children().slice(1).hide()
},renderViewList:function(){var e=this.$(".list-panel .views").empty();this.collection.each(function(a){var i=t(c.viewListItem({name:a.get("name"),viewUrl:o.getUrl(a.get("solution"),a.get("path"),a.get("file"),a.get("name"))}));
i.data("model",a),e.append(i)})},clickTab:function(e){var a=t(e.target),i=a.data("target");
this.$(".tab").removeClass("selected"),a.addClass("selected"),this.$(".panel").hide(),this.$(i).show()
},toggleViewManager:function(){this.$(".manage-views").toggleClass("active"),this.$(".view-manager").toggle()
},saveView:function(){var a=this,i=a.$(".save-properties .name").val().trim(),l=a.$(".save-properties .description").val(),r=a.model.get("dashboard");
if(!i||!i.length||"Unsaved"===i)return e.warn("Failed to save a dashboard view with no name or with the reserved name 'Unsaved'"),void 0;
var c=r.view?new s(r.view):new s;c.set("name",i,{silent:!0}),c.set("description",l,{silent:!0}),c.set("params",n.encode(JSON.stringify(r.getViewParameters())),{silent:!0}),c.set("unbound",r.getUnboundParameters(),{silent:!0}),c.set("user",r.context.user,{silent:!0}),c.set("solution",r.context.solution,{silent:!0}),c.set("path",r.context.path,{silent:!0}),c.set("file",r.context.file,{silent:!0}),c.set("timestamp",(new Date).getTime(),{silent:!0});
var d=a.collection.filter(function(e){return e.get("name")==i});t.isArray(d)&&d.length>0&&c.set("id",d[0].get("id"),{silent:!0}),c.sync("update",c,{url:o.getViewsEndpoint(i),contentType:"application/json",dataType:"json",processData:!1,data:"view="+JSON.stringify(c.toJSON()),success:function(t){return"error"===t.status?(e.warn(t.message),void 0):(r.view=t.result,r.restoreView(),a.collection.add(r.view,{merge:!0,silent:!1}),void 0)
},cache:!1})},deleteView:function(a){var i,n=this,s=t(a.target).parent().data("model").get("name").trim(),l=n.model.get("dashboard");
if(!s||!s.length)return e.warn("Failed to delete a dashboard view with no name"),void 0;
var r=n.collection.filter(function(e){return e.get("name")==s})[0];r&&(i=r),i.sync("delete",i,{url:o.getViewsEndpoint(s),contentType:"application/json",dataType:"json",success:function(t){return"error"===t.status?(e.warn(t.message),void 0):(n.collection.remove(i,{silent:!1}),l.view&&l.view.name===s&&(l.view.id=null),void 0)
},cache:!1})}});return d}),define("cde/components/ViewManagerComponent",["cdf/components/BaseComponent","cdf/lib/jquery","./ViewManager/ViewManagerModel","./ViewManager/ViewManagerView","css!./ViewManagerComponent"],function(e,t,a,i){var n=e.extend({update:function(){this.model=new a({dashboard:this.dashboard}),this.view=new i({model:this.model,el:t("#"+this.htmlObject).get(0)})
}});return n});